package club.yuyang.community.mapper;

import club.yuyang.community.entity.Thumb;
import club.yuyang.community.entity.ThumbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThumbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int countByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int deleteByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int insert(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int insertSelective(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    List<Thumb> selectByExampleWithRowbounds(ThumbExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    List<Thumb> selectByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    Thumb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Thumb record, @Param("example") ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int updateByExample(@Param("record") Thumb record, @Param("example") ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int updateByPrimaryKeySelective(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    int updateByPrimaryKey(Thumb record);
}