package club.yuyang.community.entity;

public class Thumb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.user_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.question_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.gmt_time
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    private Long gmtTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.id
     *
     * @return the value of thumb.id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.id
     *
     * @param id the value for thumb.id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.user_id
     *
     * @return the value of thumb.user_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.user_id
     *
     * @param userId the value for thumb.user_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.question_id
     *
     * @return the value of thumb.question_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.question_id
     *
     * @param questionId the value for thumb.question_id
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.gmt_time
     *
     * @return the value of thumb.gmt_time
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public Long getGmtTime() {
        return gmtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.gmt_time
     *
     * @param gmtTime the value for thumb.gmt_time
     *
     * @mbggenerated Tue Aug 20 17:35:20 CST 2019
     */
    public void setGmtTime(Long gmtTime) {
        this.gmtTime = gmtTime;
    }
}